<?php

namespace DWM\PassengerBundle\Repository;

/**
 * PassengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerRepository extends \Doctrine\ORM\EntityRepository
{
}
